baseURL = "https://igdb.github.com/api"
languageCode = "en-us"
title = "IGDB.com API Documentation"
theme = "hugo-theme-learn"
[params]
    editURL = "https://github.com/igdb/api/blob/master/content/"
    disableSearch = true